# Generated by Django 4.1.4 on 2022-12-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('fone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Fone')),
                ('celular', models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular')),
                ('celular_is_whatsapp', models.CharField(blank=True, max_length=1, null=True, verbose_name='É WhatsApp')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serie.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CNPJ')),
                ('serie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Série')),
                ('serie_dt', models.DateTimeField(blank=True, null=True, verbose_name='Dt.Serie')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=35, null=True, verbose_name='Complemento')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('contato', models.ManyToManyField(blank=True, null=True, to='serie.contato', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'cliente',
                'ordering': ['nome'],
            },
        ),
    ]
