# Generated by Django 4.1.4 on 2022-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='insc_estadual',
            field=models.CharField(blank=True, max_length=14, verbose_name='IE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='insc_municipal',
            field=models.CharField(blank=True, max_length=14, verbose_name='Insc.Munic.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação'),
        ),
    ]
